**Numpy (Numerical Python)** is a powerful python library used for numerical computing. It provides support for arrays, matrices, and a large collection of mathematical functions to operate on these arays efficiently

In [2]:
import numpy as np

**1. ARRAY CREATION FUNCTIONS**

In [11]:
np.array([1,2,3])

array([1, 2, 3])

In [12]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

**Special Arrays**

In [13]:
np.zeros((3,3)) #Matrix of zeroes (rows,col)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((5,5)) #Matrix of ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.ones((2,5,4)) #dim,rows,col

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [16]:
np.empty((2,3)) #random values

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.89145198e-307, 2.67017691e-306, 1.05699581e-307]])

In [17]:
np.eye(3) #Identity matrix or np.identity(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# Create a 2x3 array filled with 7
np.full((2, 3), 7) #np.full(shape, value) → fills with any constant you choose

array([[7, 7, 7],
       [7, 7, 7]])

**Range Arrays**

In [19]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [21]:
np.linspace(0,1,5) #start, end, Num of points to generate btw start and end

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

**2. Array Attributes**

In [22]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
arr.shape #dimensions 

(4, 3)

In [24]:
arr.ndim #number of dimensions

2

In [25]:
arr.size #total elements

12

In [26]:
arr.dtype #datatype

dtype('int64')

In [27]:
arr.itemsize #size of one element in bytes
arr.nbytes   #total bytes consumed by the array (arr.size * arr.itemsize)

96

**3. Array Reshaping**

In [28]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

The original array remains unchanged unless you explicitly assign the reshaped result back to the same variable.   *arr = arr.reshape(6,2)*

In [29]:
#Transpose - converts rows to cols and cols to rows

arr.transpose() #or
arr.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [30]:
arr.flatten() #Flattens into 1D (copy of the array)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
# Example forc flatten and ravel
# Create a 2D array
arr1 = np.array([[1, 2, 3],
                [4, 5, 6]])

# Flatten → always returns a copy
flat = arr1.flatten()
print("Flatten result:", flat)

# Ravel → returns a view when possible
rav = arr1.ravel()
print("Ravel result:", rav)

# Modify the flatten output
flat[1] = 77
print("After modifying flatten:\n", arr1)

# Modify the ravel output
rav[0] = 99
print("After modifying ravel:\n", arr1)

Flatten result: [1 2 3 4 5 6]
Ravel result: [1 2 3 4 5 6]
After modifying flatten:
 [[1 2 3]
 [4 5 6]]
After modifying ravel:
 [[99  2  3]
 [ 4  5  6]]


**4. Indexing and Slicing**

In [33]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
arr[0]

array([1, 2, 3])

In [35]:
arr[1:4]

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [36]:
arr[:,1]

array([ 2,  5,  8, 11])

In [37]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [38]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [3]:
s = np.array([10,20,30,40,50])

array([50])

In [5]:
s[0]

np.int64(10)

In [7]:
s[1:4]  #Start : end+1

array([20, 30, 40])

In [6]:
s[0:]

array([10, 20, 30, 40, 50])

In [8]:
s[-1]

np.int64(50)

**5. Numpy Mathematical Functions**

In [39]:
a = 20
b = 10

In [40]:
np.add(a,b)

np.int64(30)

In [41]:
np.subtract(a,b)

np.int64(10)

In [42]:
np.multiply(a,b)

np.int64(200)

In [43]:
np.divide(a,b)

np.float64(2.0)

In [44]:
np.divide(200,5)

np.float64(40.0)

In [45]:
np.power(2,3) #2**3

np.int64(8)

In [46]:
find_power = np.array([1,2,3,4,5])
exp = np.power(find_power,2)
exp

array([ 1,  4,  9, 16, 25])

In [47]:
np.mod(50,20) #remainder 50/20=10

np.int64(10)

**Aggregate Functions**

In [77]:
np.sum(arr)
np.mean(arr)
np.median(arr)
np.std(arr)
np.var(arr)
np.percentile()
np.quantile()
np.min(arr)
np.max(arr)

np.int64(12)

In [78]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [79]:
np.mean(arr,axis=0) #Average column-wise

array([5.5, 6.5, 7.5])

In [80]:
np.mean(arr,axis=1) #Average row-wise

array([ 2.,  5.,  8., 11.])

**Axis Operators**

In [49]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [50]:
np.sum(arr, axis=0) #sum of each column

array([22, 26, 30])

In [51]:
np.sum(arr, axis=1) #sum of each row

array([ 6, 15, 24, 33])

**6. Universal Functions**

In [52]:
np.sqrt(arr)
np.exp(arr) #applies exponential (e^x) to each element
np.log(arr)
np.sin(arr)
np.cos(arr)
np.tan(arr)
np.abs(arr) #returns absolute value of each element

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

**7. Random Functions**

In [53]:
np.random.rand(3,3) #random numbers from uniform distribution [0,1)

array([[0.52415906, 0.50446092, 0.8435335 ],
       [0.32781154, 0.34435618, 0.72777185],
       [0.05588165, 0.69772168, 0.32855701]])

In [54]:
np.random.randn(3,3) #3x3 matrix with values that can be negative or positive  
                     #random numbers from standard normal distribution (mean=0, std=1)

array([[ 0.48253334, -1.49187028, -1.56030454],
       [-0.95089443, -0.70418829, -0.12380592],
       [-0.05230673,  1.45560025, -1.10080607]])

In [55]:
np.random.randint(1,10) #single random integer between 1 and 9

4

In [56]:
np.random.randint(1,100,(3,3)) #3x3 matrix of random integers between 1 and 99

array([[20, 90, 31],
       [ 4, 51,  8],
       [99, 24, 57]], dtype=int32)

In [57]:
np.random.seed(0) #sets the seed for reproducibility
# Ensures the same random numbers are generated each time

In [58]:
np.random.seed(0)          # fix the seed before a random cell to get same random numbers everytime
print(np.random.randint(1,999,(2,2))) # always the same output

[[685 560]
 [630 193]]


**8. Array Operators**

**Joining arrays**

In [59]:
A1D = np.array([11,22,33])
B1D = np.array([44,55,66])

In [60]:
A1D,B1D

(array([11, 22, 33]), array([44, 55, 66]))

In [61]:
np.concatenate((A1D,B1D)) #joins along an existing axis

array([11, 22, 33, 44, 55, 66])

In [62]:
np.vstack((A1D,B1D)) #stacks vertically (row-wise)

array([[11, 22, 33],
       [44, 55, 66]])

In [63]:
np.hstack((A1D,B1D)) #stacks horizontally (column-wise)

array([11, 22, 33, 44, 55, 66])

In [64]:
A2D = np.array([[1,2,3,4]])
B2D = np.array([[4,5,6,7]])

print("concatenate axis=0:\n", np.concatenate((A2D,B2D), axis=0))

print("\nconcatenate axis=1:\n", np.concatenate((A2D,B2D), axis=1))


print("\nvstack:\n", np.vstack((A2D,B2D)))

print("\nhstack:\n", np.hstack((A2D,B2D)))

concatenate axis=0:
 [[1 2 3 4]
 [4 5 6 7]]

concatenate axis=1:
 [[1 2 3 4 4 5 6 7]]

vstack:
 [[1 2 3 4]
 [4 5 6 7]]

hstack:
 [[1 2 3 4 4 5 6 7]]


**Splitting arrays**

In [65]:
arrr = np.arange(12)
arrr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
np.split(arrr,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [67]:
np.split(arrr,2)

[array([0, 1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])]

In [68]:
#np.vsplit(arrr,2)
#np.hsplit(arrr,2)

**9. Matrix Operators**

In [69]:
x = np.array([[1,2],
              [3,4]])

y = np.array([[5,6],
              [7,8]])

In [70]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [71]:
np.matmul(x,y)

array([[19, 22],
       [43, 50]])

In [72]:
np.matmul(x,y)
np.linalg.inv(x)
np.linalg.det(x)
np.linalg.eig(x)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

**10. Broadcasting**

In [73]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [74]:
arr + 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [75]:
arr * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

**11. Searching Functions**

In [89]:
#np.where() - Returns indices (or values) where a condition is true.

arr3 = np.array([10, 20, 30, 0, 40])
indices = np.where(arr3 > 25)
print(indices)

values = np.where(arr3 > 25, arr3, -1)
print(values) 

(array([2, 4]),)
[-1 -1 30 -1 40]


In [90]:
#Returns the index of the maximum value in the array
np.argmax(arr3)

np.int64(4)

In [91]:
#Returns the index of the minimum value in the array
np.argmin(arr3)

np.int64(3)

In [92]:
#Returns indices of all non-zero elements. It’s similar to np.where(arr != 0)
np.nonzero(arr3)

(array([0, 1, 2, 4]),)

In [94]:
np.sort(arr3)

array([ 0, 10, 20, 30, 40])

In [96]:
np.unique(arr3)

array([ 0, 10, 20, 30, 40])

In [97]:
np.argsort(arr3) #Returns indices that sort the array

array([3, 0, 1, 2, 4])