<a href="https://colab.research.google.com/github/Gnana-Prashanth/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Creation of Numpy array

In [ ]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
arr_2d = np.array([[1,2,2],[3,4,4]])
arr_2d

array([[1, 2, 2],
       [3, 4, 4]])

In [ ]:
z= np.zeros((3,3) , dtype = int)
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
o = np.ones((3,4), dtype = int)
o

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
o = np.ones((3,4), dtype = int) * 10
o

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [ ]:
ar = np.arange(0,30, 2) # steps
ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
lp = np.linspace(0,1000,5) #starting element, last element, number of elements (Finds the equal gap between selected elements)
lp

array([   0.,  250.,  500.,  750., 1000.])

In [ ]:
r = np.random.random((2,3)) *10   #That (2,3) defines num of rows & col. That * 10 generates random numbers within 10
r

array([[9.80859521, 2.04442582, 2.77821516],
       [0.58988334, 5.93679984, 9.84384629]])

In [ ]:
ri = np.random.randint(1000,9999, (3,3))
ri

array([[2006, 7015, 4303],
       [3870, 5304, 3814],
       [8875, 8486, 7562]])

**Info about Arrays**

In [ ]:
ri.shape

(3, 3)

In [ ]:
ri.shape = (1,3,3)
ri

array([[[2006, 7015, 4303],
        [3870, 5304, 3814],
        [8875, 8486, 7562]]])

In [ ]:
ri = ri.reshape(1,9)
ri

array([[2006, 7015, 4303, 3870, 5304, 3814, 8875, 8486, 7562]])

In [ ]:
ri.size

9

In [ ]:
ri.ndim

2

In [ ]:
ri.dtype

dtype('int64')

In [ ]:
print(np.sum([[10,20],[50,60]]))              #Addition in one-array

140


In [ ]:
print(np.sum([[10,20],[50,60]] , axis =1))    #axis=1 --> Adds row-wise

[ 30 110]


In [ ]:
print(np.sum([[10,20],[50,60]] , axis =0))    #axis=0 --> Adds column-wise

[60 80]


In [ ]:
print(np.subtract([[10,20],[50,60]], [[3,12],[50,50]]))    #Subraction between two-arrays

[[ 7  8]
 [ 0 10]]


In [ ]:
print(np.add([[10,20],[50,60]], [[3,12],[50,50]]))         #Addition between two-arrays

[[ 13  32]
 [100 110]]


In [ ]:
print(np.multiply([[10,20],[3,5]], [[1,2],[5,6]]))        #Normal multiplication

[[10 40]
 [15 30]]


In [ ]:
print(np.matmul([[10,20],[3,5]], [[1,2],[5,6]]))          #matrixmul --> Row by column multiplication like in matrix

[[110 140]
 [ 28  36]]


In [ ]:
print(np.divide([[10,20],[30,15],[10,50]], [[10,4],[6,5],[4,50]]))

[[1.  5. ]
 [5.  3. ]
 [2.5 1. ]]


In [ ]:
print(np.exp(r))
print(np.sqrt(ri))
print(np.sin(ri))
print(np.cos(ri))
print(np.log(ri))
print(np.min(ri))
print(np.max(ri))
print(np.mean(ri))
print(np.median(ri))
print(np.std(ri))
print(np.var(ri))

[[1.81894168e+04 7.72472192e+00 1.60902768e+01]
 [1.80377797e+00 3.78721019e+02 1.88420488e+04]]
[[44.78839135 83.75559683 65.59725604 62.20932406 72.82856582 61.75759063
  94.20721841 92.11948762 86.95976081]]
[[ 9.95670191e-01  1.75482120e-01 -8.31573886e-01 -4.27882993e-01
   8.36903217e-01  1.06317226e-01 -7.53608763e-04 -5.29696458e-01
  -1.85403838e-01]]
[[-0.09295629 -0.98448262  0.55541414  0.90383414  0.5473509   0.99433226
  -0.99999972 -0.84818728 -0.98266241]]
[[7.60389797 8.85580599 8.36706773 8.26100979 8.57621653 8.24643379
  9.09099361 9.04617303 8.93089098]]
2006
8875
5692.777777777777
5304.0
2253.347572823735
5077575.283950617


In [ ]:
a = [1,2,3]                                #not used much
b = [4,5,6]
c = [1,2,3]
np.equal(a,b)

array([False, False, False])

In [ ]:
np.equal(a,c)

array([ True,  True,  True])

In [ ]:
np.array_equal(a,b)

False

In [ ]:
a = np.array([1,2,3])                       #Stacking Array --> combining multiple arrays into one (useful). Can be done more than 1 row also
b = np.array([4,5,6])

np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.hstack((a,b))                            #Arranges horizontally - same as concatenate

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.hstack((a,b,a))

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [ ]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

*Indexing*

In [ ]:
r = np.random.randint(1,100,(4,4))
r

array([[16, 48, 94, 69],
       [31, 21, 95, 79],
       [17, 93, 83, 19],
       [76, 40, 26, 27]])

In [ ]:
r

array([[16, 48, 94, 69],
       [31, 21, 95, 79],
       [17, 93, 83, 19],
       [76, 40, 26, 27]])

In [ ]:
r[0]

array([16, 48, 94, 69])

In [ ]:
r[0][1]

np.int64(48)

In [ ]:
r[2][3]

np.int64(19)

In [ ]:
r[::,::]             #default starts from zero index

array([[16, 48, 94, 69],
       [31, 21, 95, 79],
       [17, 93, 83, 19],
       [76, 40, 26, 27]])

In [ ]:
r[1::,2::]         #[::,::] --> [rows,col]

array([[95, 79],
       [83, 19],
       [26, 27]])

In [ ]:
r[1:3:1,:4:1]      #start:end:gaps  --> by default gap is 1, if we want end end=end+1

array([[31, 21, 95, 79],
       [17, 93, 83, 19]])

In [ ]:
r[1:3:2,::]

array([[31, 21, 95, 79]])

In [ ]:
r[1:4:2,::]

array([[31, 21, 95, 79],
       [76, 40, 26, 27]])

In [ ]:
r[:3:2,2:3:]

array([[94],
       [83]])

In [ ]:
r[-1:0:-1,::]

array([[76, 40, 26, 27],
       [17, 93, 83, 19],
       [31, 21, 95, 79]])

In [ ]:
r[::3,::3]

array([[16, 69],
       [76, 27]])

In [ ]:
r[:2:,:0:-1]

array([[69, 94, 48],
       [79, 95, 21]])

In [ ]:
r[::2,1:2:]

array([[48],
       [93]])

**Numpy Handson**

In [ ]:
x=np.array(['string',20,4.11])   #We can give multiple datatypes as input
x

array(['string', '20', '4.11'], dtype='<U32')

Every output is returned in string format.
Beacause the Priorities are:
1.STRING
2.FLOAT
3.INT












In [ ]:
x1=np.array([20,4.11])   #Now it will store as float (20.,4.11)
x1

array([20.  ,  4.11])

In [ ]:
x1.dtype

dtype('float64')

1. Create a numpy array with numpy.array module and with a data type integer and float.

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([2.9,7.21,9.0],dtype=float)

print(a.dtype)
print(b.dtype)

int64
float64


2. Create numpy arrays that have zero, one, two, three, Four dimensions respectively.
Also, print the shape and dimensions of the numpy arrays created above.

In [ ]:
# 0-D array (scalar)
arr0 = np.array(42)
print("0-D Array:", arr0)
print("Shape:", arr0.shape, "Dimensions:", arr0.ndim, "\n")

# 1-D array (vector)
arr1 = np.array([1, 2, 3, 4, 5])
print("1-D Array:", arr1)
print("Shape:", arr1.shape, "Dimensions:", arr1.ndim, "\n")

# 2-D array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2-D Array:\n", arr2)
print("Shape:", arr2.shape, "Dimensions:", arr2.ndim, "\n")

# 3-D array (cube-like)
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3-D Array:\n", arr3)
print("Shape:", arr3.shape, "Dimensions:", arr3.ndim, "\n")

# 4-D array
arr4 = np.array([[[[1, 2], [3, 4]]]])
print("4-D Array:\n", arr4)
print("Shape:", arr4.shape, "Dimensions:", arr4.ndim, "\n")

#Number of dimensions can be decided by seeing their [] brackets

0-D Array: 42
Shape: () Dimensions: 0 

1-D Array: [1 2 3 4 5]
Shape: (5,) Dimensions: 1 

2-D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3) Dimensions: 2 

3-D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2) Dimensions: 3 

4-D Array:
 [[[[1 2]
   [3 4]]]]
Shape: (1, 1, 2, 2) Dimensions: 4 



3.Create a 2x3, 3x3, and 4x4 identity matrix using numpy.

In [ ]:
x = np.eye(2,3)  #bcz 2*3 is invalid (inequal) for identity matrix
y = np.identity(3)
z = np.identity(4)

print(x)
print(y)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


4. Create a numpy array with shape 2x5 that has all the elements as zero.

In [ ]:
z = np.zeros((2,5) , dtype = int)
z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

5. Create a numpy array that has the shape 3x5 and all the elements are 5.

In [ ]:
y = np.full((3,5),5)  #can use another method also
y

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

6. Create a numpy array with random integers in the range 0-100, and the sample size
should be 25.

In [ ]:
arr = np.random.randint(0, 101, size=25)
arr

array([88,  3, 76, 85, 26, 14, 61,  2, 30, 77, 93, 81, 12, 91, 61, 21,  2,
       10, 26,  4, 88,  9, 97, 33, 57])

7. Create a numpy array with a shape 3x3 that has all elements as 1.

In [ ]:
o = np.ones((3,3), dtype = int)
o

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

8. Create a numpy array in the shape 2x3 with random integers in the range 0-100.
Reshape the array in the shape 3x2 and print the updated shape of the resultant array.

In [ ]:
arr = np.random.randint(0,101,(2,3))
print(arr)

re_arr = arr.reshape(3,2)
print(re_arr)

[[ 54 100  70]
 [ 24  34  59]]
[[ 54 100]
 [ 70  24]
 [ 34  59]]


In [ ]:
re_arr.shape

(3, 2)

9. Create a random array, with the range 0-1000, with a size 50 . Perform the
following operations on the same.
a. Print the first ten elements of the array.
b. Print the last ten elements of the array
c. Print the elements from the indexes 10-25
d. Print the element at the index 22
e. Print the array using negative indexing.
f. Print the last ten elements of the array, using negative indexing.


In [ ]:
rand = np.random.randint(0,1001, size = 50)
print("Full array:\n",rand, "\n")

#a. First 10 elements
print("First 10 elements:", rand[:10])

#b. Last 10 elements
print("Last 10 elements:", rand[-10:])

#c
print("Elements from index 10 to 25:", rand[10:26])

#d
print("Ele in index 22:", rand[22],"\n")

#e. Array using negative indexing (reverses the array)
print("Array reversed:\n", rand[::-1], "\n")

#f
print("last 10 elements using neg index:", rand[-10:])

Full array:
 [  35  884   53  537  567  900  474  595  912  704  900  601  273   89
  533  798   55  319  187  561  298  685  167   71  983  660  312  608
  819  356  532  900  344  191   95  759   84   47  329 1000  378  573
   96  968  325   27  592  205  358  844] 

First 10 elements: [ 35 884  53 537 567 900 474 595 912 704]
Last 10 elements: [378 573  96 968 325  27 592 205 358 844]
Elements from index 10 to 25: [900 601 273  89 533 798  55 319 187 561 298 685 167  71 983 660]
Ele in index 22: 167 

Array reversed:
 [ 844  358  205  592   27  325  968   96  573  378 1000  329   47   84
  759   95  191  344  900  532  356  819  608  312  660  983   71  167
  685  298  561  187  319   55  798  533   89  273  601  900  704  912
  595  474  900  567  537   53  884   35] 

last 10 elements using neg index: [378 573  96 968 325  27 592 205 358 844]


10. Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations.
a. Insert the element 6 at the end of the array.
b. Insert the element 10 at the beginning of the array.
c. Insert the element 30, before 4.
d. Update the element 5 as 50.
e. Delete the element 50 in the updated array.
f. Sort the array in ascending order.
g. Sort the array in descending order.


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)

arr = np.append(arr,6)
print("After inserting 6 at end:", arr)

arr=np.insert(arr,0,10)
print("After Inserting the ele 10 at the beg:",arr)

arr=np.insert(arr,4,30)
print(arr)

arr[arr == 5] = 50
print("After updating 5 as 50:", arr)

arr = arr[arr != 50]
print("After deleting 50:", arr)

arr = np.sort(arr)
print("Sorted arr:",arr)


arr = np.sort(arr)[::-1]
print("Sorted arr in descending:",arr)

[1 2 3 4 5]
After inserting 6 at end: [1 2 3 4 5 6]
After Inserting the ele 10 at the beg: [10  1  2  3  4  5  6]
[10  1  2  3 30  4  5  6]
After updating 5 as 50: [10  1  2  3 30  4 50  6]
After deleting 50: [10  1  2  3 30  4  6]
Sorted arr: [ 1  2  3  4  6 10 30]
Sorted arr in descending: [30 10  6  4  3  2  1]


Create a **1-D NumPy array of 20 random integers** between **10 and 100**.  
Print the following:
* Mean  
* Median  
* Standard Deviation  
* Variance  


In [ ]:
x = np.random.randint(10, 101, size=20)
print("Random Numbers:", x)
mean=np.mean(x)
print("Mean:",mean)
median=np.median(x)
print("median:",median)
std=np.std(x)
print("Standard deviation:",std)
var=np.var(x)
print("Variance:",var)

Random Numbers: [50 86 19 11 42 56 27 11 34 63 60 20 57 17 85 34 68 76 55 65]
Mean: 46.8
median: 52.5
Standard deviation: 23.47040689890143
Variance: 550.8599999999999


In [ ]:
#cross and dot products
